### ISSUE TITLE
User specific config directory?

### ISSUE THREAD

**Issue by marhop** [veraPDF/veraPDF-library#1004]
## Dev Effort
2D

## Description
The current installation routine (installer v0.26.16) puts the veraPDF config directory inside the program installation directory (`<install_dir>/config/`). This is okay for a private, single-user installation where `<install_dir>` would be something like `~/bin/verapdf/` (examples based on Linux, but I guess on Windows it's similar). But if we want to install veraPDF system-wide for all users, `<install_dir>` will probably be a location that is writable only by root, like `/opt/verapdf/`. This leads to errors when starting the program as a regular, non-root user.

Please move the config directory from the installation directory to a user specific path, at least in case `<install_dir>/config/` is not writable! Possible locations include `~/.verapdf/` or `~/.config/verapdf/` on Linux and somewhere below `%APPDATA%` on Windows.

---

Steps to reproduce:

 1. Run the installer on Linux as root/sudo.
 2. Choose `/opt/verapdf/` as installation directory to prepare a system-wide installation. (Optionally, manually create a symlink `/usr/local/bin/verapdf -> /opt/verapdf/verapdf` later to make the verapdf command available in the users' path.)
 3. After the installation has finished, run the `/opt/verapdf/verapdf` starter script as a regular user.
 4. An exception is thrown:

        Exception in thread "main" java.lang.ExceptionInInitializerError
        Caused by: java.lang.IllegalArgumentException: Arg root:/opt/verapdf/config, must be a writable directory.
                at org.verapdf.apps.Applications.createConfigManager(Applications.java:36)
                at org.verapdf.apps.Applications.createAppConfigManager(Applications.java:44)
                at org.verapdf.cli.VeraPdfCli.<clinit>(VeraPdfCli.java:31)

**Comment by marhop** [comment]
Hi, any updates on this?

Cheers,
Martin
