### ISSUE TITLE
NPE in TransparencyGraphicsState.copyPropertiesFormExtGState()

### ISSUE THREAD

**Issue by THausherr** [veraPDF/veraPDF-library#1016]
```
Caused by: java.lang.NullPointerException
        at org.verapdf.gf.model.factory.operators.TransparencyGraphicsState.copyPropertiesFormExtGState(TransparencyGraphicsState.java:141)
        at org.verapdf.gf.model.factory.operators.OperatorParser.processExtGState(OperatorParser.java:478)
        at org.verapdf.gf.model.factory.operators.OperatorParser.parseOperator(OperatorParser.java:123)
        at org.verapdf.gf.model.factory.operators.OperatorFactory.operatorsFromTokens(OperatorFactory.java:110)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.parseOperators(GFPDContentStream.java:111)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.isContainsTransparency(GFPDContentStream.java:140)
```
[lean-from-the-trenches.pdf](https://github.com/veraPDF/veraPDF-library/files/2818963/lean-from-the-trenches.pdf)

Version 1.12.1 (from today) on Windows 7.

**Comment by BezrukovM** [comment]
fixed in 1.13.28
