### ISSUE TITLE
Differences between Greenfield and PdfBox implementations

### ISSUE THREAD

**Issue by kalinmarkov95** [veraPDF/veraPDF-library#1024]
Hello, 
When using the pdfbox latest version(1.4.5), the library throws the following exception when trying to validate a file for pdfa:

```
java.util.NoSuchElementException: PDFAFlavour 0 is not supported by this directory.
        at org.verapdf.pdfa.validation.profiles.ProfileDirectoryImpl.getValidationProfileByFlavour(ProfileDirectoryImpl.java:104) ~[decom-desktop-1.1.2-jar-with-dependencies.jar:?]
        at org.verapdf.pdfa.validation.validators.ValidatorFactory.createValidator(ValidatorFactory.java:69) ~[decom-desktop-1.1.2-jar-with-dependencies.jar:?]
        at org.verapdf.pdfa.AbstractFoundry.createValidator(AbstractFoundry.java:62) ~[decom-desktop-1.1.2-jar-with-dependencies.jar:?]
```

However, when I switch to using the Greenfield latest version(1.12.1) for the same file, the library does not throw any error anymore but instead simply states that the file is not pdfa. Any ideas about the reason? Could this be a bug in the pdfbox version? Do you suggest I switch to the Greenfield version - I am considering this but hope that it doesn't mess something else up.

Thank you very much!

**Comment by bdoubrov** [comment]
PDFAFlavour 0 means the validator has to derive the PDF/A flavour from the document metadata. The support for this was indeed added after version 1.4 was released.

If you think your file does comply to PDF/A, but veraPDF is reporting any validation errors, please provide your PDF to check it in more detail.
