### ISSUE TITLE
An error occurred when vidating pdf (PDFParser::GetDictionary()invalid pdf dictonary)

### ISSUE THREAD

**Issue by sify21** [veraPDF/veraPDF-library#1042]
I'm using gofpdf to generate pdf files. 
[hello.pdf](https://github.com/veraPDF/veraPDF-library/files/3640535/hello.pdf)
When validating the generated pdf, verapdf crashed with an exception.
```
Sep 20, 2019 3:50:21 PM org.verapdf.processor.ProcessorImpl validate
WARNING: Exception caught when validating item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:95)
	at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:118)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:53)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Error while parsing object : 5 0
	at org.verapdf.cos.COSDocument.getObject(COSDocument.java:226)
	at org.verapdf.cos.COSIndirect.getDirect(COSIndirect.java:368)
	at org.verapdf.gf.model.visitor.cos.pb.GFCosVisitor.visitFromIndirect(GFCosVisitor.java:137)
	at org.verapdf.gf.model.impl.cos.GFCosObject.getFromValue(GFCosObject.java:70)
	at org.verapdf.gf.model.impl.cos.GFCosDict.getValues(GFCosDict.java:115)
	at org.verapdf.gf.model.impl.cos.GFCosDict.getLinkedObjects(GFCosDict.java:86)
	at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:199)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:166)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:117)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:93)
	... 13 more
Caused by: java.io.IOException: PDFParser::GetDictionary()invalid pdf dictonary
	at org.verapdf.parser.COSParser.getDictionary(COSParser.java:250)
	at org.verapdf.parser.COSParser.nextObject(COSParser.java:179)
	at org.verapdf.parser.PDFParser.getObject(PDFParser.java:282)
	at org.verapdf.io.Reader.getObject(Reader.java:122)
	at org.verapdf.io.Reader.getObject(Reader.java:95)
	at org.verapdf.cos.COSDocument.getObject(COSDocument.java:217)
	... 22 more
```
I also reported a similar [issue](https://github.com/jung-kurt/gofpdf/issues/304#issue-496294130) to gofpdf. The author of gofpdf says maybe it's something wrong with his library. I wonder what caused verapdf to crash, which may be helpful for fixing the issue with gofpdf.

**Comment by THausherr** [comment]
Please share the PDF file.

**Comment by sify21** [comment]
@THausherr I added the file in the issue.

**Comment by THausherr** [comment]
The error is this: "/BaseFont /utf8noto sans scB". The spaces are wrong.

**Comment by sify21** [comment]
@THausherr I removed the spaces in fontname, but it still reports error.
[hello_bad2.pdf](https://github.com/veraPDF/veraPDF-library/files/3640833/hello_bad2.pdf)

**Comment by THausherr** [comment]
Yes it has errors because it is not valid PDF/A. But now it parses.

**Comment by sify21** [comment]
Oh I see. Thanks for the help
