### ISSUE TITLE
Issue with java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error while parsing object

### ISSUE THREAD

**Issue by somayalangley-usyd** [veraPDF/veraPDF-library#1065]
I’ve been able to replicate the same issue with VeraPDF on two different computers – though I should specify that the “error while parsing object” occurs at different points on the 2 x different PCs. Issue has appeared twice (in two different locations), tested across two completely different PCs (with the same builds), on the same set of PDF/A files (PDF/A-1b) which have all been recognised as this by DROID. 

Details of both PCs:
•	OS: Windows 10
•	JAVA: Version 8 - update 241
•	VERAPDF: verapdf-izpack-installer-1.14.8.jar

Have run issue past Carl Wilson and he advises the following:
"I've had a look at your issue and it appears to me that the root cause is a veraPDF issue caused by a null object stream. My belief is that the software should handle this more gracefully than it currently does so feel free to raise an issue."

ERROR = PC #1
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error while parsing object : 645 0
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at javax.swing.SwingWorker.get(Unknown Source)
        at org.verapdf.gui.CheckerPanel.validationEnded(CheckerPanel.java:551)
        at org.verapdf.gui.ValidateWorker.done(ValidateWorker.java:158)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error while parsing object : 645 0
        at org.verapdf.cos.COSDocument.getObject(COSDocument.java:226)
        at org.verapdf.cos.COSIndirect.getDirect(COSIndirect.java:368)
        at org.verapdf.cos.COSIndirect.getKey(COSIndirect.java:217)
        at org.verapdf.cos.COSObject.getKey(COSObject.java:233)
        at org.verapdf.pd.PDObject.getKey(PDObject.java:69)
        at org.verapdf.pd.PDCatalog.getMetadata(PDCatalog.java:67)
        at org.verapdf.gf.model.GFModelParser.obtainFlavour(GFModelParser.java:118)
        at org.verapdf.gf.model.GFModelParser.<init>(GFModelParser.java:82)
        at org.verapdf.gf.model.GFModelParser.createModelWithFlavour(GFModelParser.java:104)
        at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:80)
        at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:86)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:115)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:118)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:53)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Object number 1701875798 should be object stream, but in fact it is null
        at org.verapdf.io.Reader.getObject(Reader.java:109)
        at org.verapdf.cos.COSDocument.getObject(COSDocument.java:217)
        ... 22 more
 
ERROR = PC #2
java.util.concurrent.ExecutionException: java.lang.RuntimeException: Error while parsing object : 4809 0
        at java.util.concurrent.FutureTask.report(Unknown Source)
        at java.util.concurrent.FutureTask.get(Unknown Source)
        at javax.swing.SwingWorker.get(Unknown Source)
        at org.verapdf.gui.CheckerPanel.validationEnded(CheckerPanel.java:551)
        at org.verapdf.gui.ValidateWorker.done(ValidateWorker.java:158)
        at javax.swing.SwingWorker$5.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.run(Unknown Source)
        at sun.swing.AccumulativeRunnable.run(Unknown Source)
        at javax.swing.SwingWorker$DoSubmitAccumulativeRunnable.actionPerformed(Unknown Source)
        at javax.swing.Timer.fireActionPerformed(Unknown Source)
        at javax.swing.Timer$DoPostEvent.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.lang.RuntimeException: Error while parsing object : 4809 0
        at org.verapdf.cos.COSDocument.getObject(COSDocument.java:226)
        at org.verapdf.cos.COSIndirect.getDirect(COSIndirect.java:368)
        at org.verapdf.cos.COSIndirect.getKey(COSIndirect.java:217)
        at org.verapdf.cos.COSObject.getKey(COSObject.java:233)
        at org.verapdf.pd.PDObject.getKey(PDObject.java:69)
        at org.verapdf.pd.PDCatalog.getMetadata(PDCatalog.java:67)
        at org.verapdf.gf.model.GFModelParser.obtainFlavour(GFModelParser.java:118)
        at org.verapdf.gf.model.GFModelParser.<init>(GFModelParser.java:82)
        at org.verapdf.gf.model.GFModelParser.createModelWithFlavour(GFModelParser.java:104)
        at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:80)
        at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:86)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:115)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:118)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:53)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.io.IOException: Object number 1033170915 should be object stream, but in fact it is null
        at org.verapdf.io.Reader.getObject(Reader.java:109)
        at org.verapdf.cos.COSDocument.getObject(COSDocument.java:217)
        ... 22 more

**Comment by bdoubrov** [comment]
Thanks for submitting this issue. Would it be possible to attach the PDF documents where you reproduce these exceptions?

It would also make sense to check this issue on the pre-release version 1.16.1, where a number of similar issues was already fixed.

**Comment by somayalangley-usyd** [comment]
Hi Boris and other VeraPDF developers,

I think this may be tricky as I am having to run VeraPDF over a consignment of 19966 files delivered from a vendor. I would appreciate any assistance in working out how I might identify which PDF/A files could be the issue.

My issue is that there are 1559 PDF/A files (DROID reports them as all being PDF/A-1b), and these are interspersed as Access Copy files, alongside their TIFF Preservation Masters.

Files are delivered in hierarchically-nested folders (there are 500 folders in total), and it is within this there are both a combination of PDF/A access copies and TIFF masters.


What I can’t work out, is which file (or set of files) might be getting VeraPDF to produce this error. Is there any other way I can potentially identify the files that might produce this error. I’ve been running the VeraPDF GUI, but if you let me know of a command to run in a CLI, maybe there’s a way of indicating which file VeraPDF is processing when it produces these errors?

Can you please let me know how I might identify the PDF/A(s) that might be triggering this issue from out of the over 1500 PDF/As? NB: Some are quite large in size


Thanks
Somaya

Somaya Langley | Digital Curation Manager
The University of Sydney
Access Services, University Library
Level 1, Fisher Library | The University of Sydney | NSW | 2006
+61 2 8627 9189
somaya.langley@sydney.edu.au | library.sydney.edu.au
We acknowledge the tradition of custodianship and law of the Country on which the University of Sydney campuses stand. We pay our respects to those who have cared and continue to care for Country.
CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised use is strictly prohibited.
If you receive this email in error, please delete it and any attachments.
Please think of our environment and only print this email if necessary.

**Comment by bdoubrov** [comment]
We'll add extra parameters to configure error logs so that the file name is logged into stderr if this extra parameter is specified. This would allow tracing file names that cause problems.

**Comment by bdoubrov** [comment]
Fix released in v1.20
