### ISSUE TITLE
Validation/parsing problem

### ISSUE THREAD

**Issue by heikki-tuominen** [veraPDF/veraPDF-library#1076]
In contrast to the Adobe tools, veraPDF cannot validate, maybe not even
parse, the attached document,

ahjo7460983509570359397.pdf

The validation report tells the following.

---

Validation Report
File:	C:\Users\tuomihei\Projects\Ahjo2\doc\jira\agileahjo\250\pdf\ahjo7460983509570359397.pdf
Error:	Exception: Caught unexpected runtime exception during validation caused by exception: null
Statistics
Version:	1.14.8
Parser:	GreenField
Build Date:	2019-10-24T23:11:00+03:00
Processing time:	00:00:00.307

---

The log tells the following.

---

toukokuuta 18, 2020 8:09:52 AP. org.verapdf.processor.ProcessorImpl validate
WARNING: Exception caught when validating item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:95)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:118)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:53)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
Caused by: java.lang.NullPointerException
        at org.verapdf.pd.structure.PDNumberTreeNode.getLimitsArray(PDNumberTreeNode.java:59)
        at org.verapdf.pd.structure.PDNumberTreeNode.getObject(PDNumberTreeNode.java:119)
        at org.verapdf.pd.structure.PDNumberTreeNode.getObject(PDNumberTreeNode.java:145)
        at org.verapdf.pd.structure.PDNumberTreeNode.getObject(PDNumberTreeNode.java:115)
        at org.verapdf.pd.structure.StructureElementAccessObject.getStructureElement(StructureElementAccessObject.java:50)
        at org.verapdf.gf.model.impl.operator.markedcontent.MarkedContentHelper.containsActualText(MarkedContentHelper.java:47)
        at org.verapdf.gf.model.impl.operator.textshow.GFGlyph.getactualTextPresent(GFGlyph.java:230)
        at org.verapdf.gf.model.impl.operator.textshow.GFGlyph.<init>(GFGlyph.java:110)
        at org.verapdf.gf.model.impl.operator.textshow.GFGlyph.getGlyph(GFGlyph.java:125)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getUsedGlyphs(GFOpTextShow.java:156)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getLinkedObjects(GFOpTextShow.java:115)
        at org.verapdf.gf.model.impl.operator.textshow.GFOp_TJ_Big.getLinkedObjects(GFOp_TJ_Big.java:62)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:199)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:166)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:117)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:93)
        ... 13 more

---

The problem seems to be present even in the plain PDF form of the
document, available as

https://www.hel.fi/static/sote/julkaisut/Savuton_Helsinki_loppuraportti_2016.pdf

Heikki Tuominen

[ahjo7460983509570359397.pdf](https://github.com/veraPDF/veraPDF-library/files/4642204/ahjo7460983509570359397.pdf)

**Comment by THausherr** [comment]
ouch

![grafik](https://user-images.githubusercontent.com/6665575/82184892-a5d11880-98e8-11ea-835f-9d7b2bcc4473.png)

**Comment by bdoubrov** [comment]
Yes, the document is clearly broken. We'll add a more polite reporting about this rather than throwing a null pointer exception.
