### ISSUE TITLE
Exception in org.verapdf.pd.structure.PDNumberTreeNode.getLimitsArray

### ISSUE THREAD

**Issue by thomasfischer-his** [veraPDF/veraPDF-library#1117]
Feeding the following PDF file into veraPDF 1.16.1 (latest stable version at the time of writing) causes a ValidationException, triggered by a NullPointerException, as documented further below.

PDF file: http://his.diva-portal.org/smash/get/diva2:1447648/FULLTEXT01.pdf
Available at: http://urn.kb.se/resolve?urn=urn%3Anbn%3Ase%3Ahis%3Adiva-18634

Output generated when running veraPDF on the command line without any special settings or customization:

```
<?xml version="1.0" encoding="utf-8"?>
<report>
  <buildInformation>
    <releaseDetails id="core" version="1.16.1" buildDate="2020-05-12T00:43:00+02:00"></releaseDetails>
    <releaseDetails id="validation-model" version="1.16.1" buildDate="2020-05-12T00:46:00+02:00"></releaseDetails>
    <releaseDetails id="gui" version="1.16.1" buildDate="2020-05-12T00:59:00+02:00"></releaseDetails>
  </buildInformation>
  <jobsOct 27, 2020 11:44:03 AM org.verapdf.processor.ProcessorImpl validate
WARNING: Exception caught when validating item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:95)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFilePaths(VeraPdfCliProcessor.java:167)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:132)
        at org.verapdf.cli.VeraPdfCli.singleThreadProcess(VeraPdfCli.java:133)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:101)
        at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:54)
Caused by: java.lang.NullPointerException
        at org.verapdf.pd.structure.PDNumberTreeNode.getLimitsArray(PDNumberTreeNode.java:58)
        at org.verapdf.pd.structure.PDNumberTreeNode.getObject(PDNumberTreeNode.java:119)
        at org.verapdf.pd.structure.PDNumberTreeNode.getObject(PDNumberTreeNode.java:145)
        at org.verapdf.pd.structure.PDNumberTreeNode.getObject(PDNumberTreeNode.java:115)
        at org.verapdf.pd.structure.StructureElementAccessObject.getStructureElement(StructureElementAccessObject.java:50)
        at org.verapdf.gf.model.impl.operator.markedcontent.MarkedContentHelper.containsActualText(MarkedContentHelper.java:47)
        at org.verapdf.gf.model.impl.operator.textshow.GFGlyph.getactualTextPresent(GFGlyph.java:234)
        at org.verapdf.gf.model.impl.operator.textshow.GFGlyph.<init>(GFGlyph.java:114)
        at org.verapdf.gf.model.impl.operator.textshow.GFGlyph.getGlyph(GFGlyph.java:129)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getUsedGlyphs(GFOpTextShow.java:156)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getLinkedObjects(GFOpTextShow.java:115)
        at org.verapdf.gf.model.impl.operator.textshow.GFOp_TJ_Big.getLinkedObjects(GFOp_TJ_Big.java:62)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:199)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:166)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:117)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:93)
        ... 10 more

>
    <job>
      <item size="2045561">
        <name>FULLTEXT01.pdf</name>
      </item>
      <taskResult type="VALIDATE" isExecuted="true" isSuccess="false">
        <duration start="1603795441888" finish="1603795443485">00:00:01.597</duration>
        <exceptionMessage>Exception: Caught unexpected runtime exception during validation caused by exception: null</exceptionMessage>
      </taskResult>
      <duration start="1603795441888" finish="1603795443485">00:00:01.597</duration>
    </job>
  </jobs>
  <batchSummary totalJobs="1" failedToParse="0" encrypted="0">
    <validationReports compliant="0" nonCompliant="0" failedJobs="1">1</validationReports>
    <featureReports failedJobs="0">0</featureReports>
    <repairReports failedJobs="0">0</repairReports>
    <duration start="1603795441763" finish="1603795443546">00:00:01.783</duration>
  </batchSummary>
</report>
```

**Comment by bdoubrov** [comment]
Fixed in the latest dev version 1.17.40: https://software.verapdf.org/develop/1.17/verapdf-pdfbox-1.17.40-installer.zip
