### ISSUE TITLE
IndexOutOfBoundsException

### ISSUE THREAD

**Issue by IssueReporter12345** [veraPDF/veraPDF-library#1163]
I've got a runtime "index out of bounds" exception during PDF/A-1b validation for a document (see attachment) in verapdf-1.16.1 and in verapdf-1.18.6.

[VeraPDF-Exception.pdf](https://github.com/veraPDF/veraPDF-library/files/6459102/VeraPDF-Exception.pdf)

Remark:
- The source file shows the same behavior: [woehner-31314000A_DO_Lasttrennschalter.pdf](https://github.com/veraPDF/veraPDF-library/files/6460404/woehner-31314000A_DO_Lasttrennschalter.pdf)
- Used application: RealObjects PDFreactor(R) 10.0.10722

```
OS: Windows 10, limited standard user (no admin)

verapdf.bat -f 1b

[...] org.verapdf.processor.ProcessorImpl validate
WARNUNG: Exception caught when validating item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:95)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFilePaths(VeraPdfCliProcessor.java:172)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:131)
        at org.verapdf.cli.VeraPdfCli.singleThreadProcess(VeraPdfCli.java:138)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:106)
        at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:54)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -15
        at org.verapdf.pd.font.cff.CFFIndex.get(CFFIndex.java:54)
        at org.verapdf.pd.font.cff.Type2CharStringParser.execSubr(Type2CharStringParser.java:122)
        at org.verapdf.pd.font.cff.Type2CharStringParser.processNextOperator(Type2CharStringParser.java:97)
        at org.verapdf.pd.font.type1.BaseCharStringParser.parse(BaseCharStringParser.java:131)
        at org.verapdf.pd.font.type1.BaseCharStringParser.<init>(BaseCharStringParser.java:79)
        at org.verapdf.pd.font.cff.Type2CharStringParser.<init>(Type2CharStringParser.java:52)
        at org.verapdf.pd.font.cff.CharStringsWidths.getWidthFromCharstring(CharStringsWidths.java:166)
        at org.verapdf.pd.font.cff.CharStringsWidths.parseSubsetWidths(CharStringsWidths.java:249)
        at org.verapdf.pd.font.cff.CharStringsWidths.<init>(CharStringsWidths.java:95)
        at org.verapdf.pd.font.cff.CharStringsWidths.<init>(CharStringsWidths.java:118)
        at org.verapdf.pd.font.cff.CFFType1FontProgram.readWidths(CFFType1FontProgram.java:219)
        at org.verapdf.pd.font.cff.CFFType1FontProgram.parseFont(CFFType1FontProgram.java:96)
        at org.verapdf.pd.font.cff.CFFFontProgram.parseFont(CFFFontProgram.java:90)
        at org.verapdf.gf.model.impl.pd.font.GFPDCIDFont.<init>(GFPDCIDFont.java:75)
        at org.verapdf.gf.model.impl.pd.font.GFPDType0Font.getDescendantFont(GFPDType0Font.java:95)
        at org.verapdf.gf.model.impl.pd.font.GFPDType0Font.<init>(GFPDType0Font.java:57)
        at org.verapdf.gf.model.factory.fonts.FontFactory.parseFont(FontFactory.java:74)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.parseFont(GFOpTextShow.java:219)
        at org.verapdf.gf.model.impl.operator.textshow.GFOpTextShow.getVeraModelFont(GFOpTextShow.java:155)
        at org.verapdf.gf.model.factory.operators.OperatorParser.addFontAndColorSpace(OperatorParser.java:620)
        at org.verapdf.gf.model.factory.operators.OperatorParser.parseOperator(OperatorParser.java:305)
        at org.verapdf.gf.model.factory.operators.OperatorFactory.operatorsFromTokens(OperatorFactory.java:110)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.parseOperators(GFPDContentStream.java:148)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.isContainsTransparency(GFPDContentStream.java:177)
        at org.verapdf.gf.model.impl.pd.GFPDPage.parseContentStream(GFPDPage.java:212)
        at org.verapdf.gf.model.impl.pd.GFPDPage.getContentStream(GFPDPage.java:193)
        at org.verapdf.gf.model.impl.pd.GFPDPage.getLinkedObjects(GFPDPage.java:118)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:199)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:166)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:117)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:93)
        ... 10 more

```

Possibly a regression of [https://github.com/veraPDF/veraPDF-library/issues/701]

**Comment by bdoubrov** [comment]
Fix released in v1.20
