### ISSUE TITLE
A PDF with a missing Resources dictionary will cause a NullPointerException during validation

### ISSUE THREAD

**Issue by jorisschellekens** [veraPDF/veraPDF-library#1189]
A PDF with a page with a missing Resources dictionary will cause a NullPointerException.

```java
WARNING: Exception caught when validating item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:95)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFilePaths(VeraPdfCliProcessor.java:172)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:131)
        at org.verapdf.cli.VeraPdfCli.singleThreadProcess(VeraPdfCli.java:138)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:106)
        at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:54)
Caused by: java.lang.NullPointerException
        at org.verapdf.gf.model.impl.pd.util.PDResourcesHandler.getColorSpace(PDResourcesHandler.java:121)
        at org.verapdf.gf.model.factory.operators.GraphicState.<init>(GraphicState.java:52)
        at org.verapdf.gf.model.factory.operators.OperatorParser.<init>(OperatorParser.java:106)
        at org.verapdf.gf.model.factory.operators.OperatorFactory.operatorsFromTokens(OperatorFactory.java:104)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.parseOperators(GFPDContentStream.java:148)
        at org.verapdf.gf.model.impl.pd.GFPDContentStream.isContainsTransparency(GFPDContentStream.java:177)
        at org.verapdf.gf.model.impl.pd.GFPDPage.parseContentStream(GFPDPage.java:212)
        at org.verapdf.gf.model.impl.pd.GFPDPage.getContentStream(GFPDPage.java:193)
        at org.verapdf.gf.model.impl.pd.GFPDPage.getLinkedObjects(GFPDPage.java:118)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:199)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:166)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:117)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:93)
        ... 10 more
```

This is not exactly helpful. Vera should just report the information in `ISO 32000-2, Table 31 — Entries in a page object`

Kind regards,
Joris Schellekens

**Comment by bdoubrov** [comment]
Fix released in v1.20
