### ISSUE TITLE
Eclipse Maven Project with 1.20.1: java.lang.SecurityException: class "org.verapdf.pdfa.VeraFoundryProvider"'s signer information does not match signer information of other classes in the same package

### ISSUE THREAD

**Issue by thomasgundlach** [veraPDF/veraPDF-library#1231]
Good Evening,

greate project. Using for long time the CLI. Always works fine. Now i tried the Java API and run into a problem.

I'm using Eclipse Version: 2021-12 (4.22.0) Build id: 20211202-1639. I'm trying to  run the example of https://docs.verapdf.org/develop/ with your last stable release (1.20.1):
```
package org.mrbself.testvera;

import org.verapdf.pdfa.VeraGreenfieldFoundryProvider;

import java.io.FileInputStream;
import java.io.IOException;

import org.verapdf.core.EncryptedPdfException;
import org.verapdf.core.ModelParsingException;
import org.verapdf.core.ValidationException;
import org.verapdf.pdfa.Foundries;
import org.verapdf.pdfa.PDFAParser;
import org.verapdf.pdfa.results.ValidationResult;
import org.verapdf.pdfa.PDFAValidator;

/**
 * Hello world!
 *
 */
public class App 
{
    public static void main( String[] args )
    {
    	VeraGreenfieldFoundryProvider.initialise();
    	try (PDFAParser parser = Foundries.defaultInstance().createParser(new FileInputStream("T:\\gundlach\\pdfa\\Kodak-1A12-CMCID_00008585_TestA.pdf"))) {
    	    PDFAValidator validator = Foundries.defaultInstance().createValidator(parser.getFlavour(), false);
    	    ValidationResult result = validator.validate(parser);
    	    if (result.isCompliant()) {
    	      // File is a valid PDF/A 1b
    	    } else {
    	      // it isn't
    	    }
    	} catch (IOException | ValidationException | ModelParsingException | EncryptedPdfException exception) {
    		// Exception during validation
    	}
    }
}
```

In a basic eclipse maven project of org.apache.maven.archetypes -> maven-archetype-quickstart -> 1.4 With the following POM:
```
<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>org.mrbself</groupId>
  <artifactId>testvera</artifactId>
  <version>0.0.1-SNAPSHOT</version>

  <name>testvera</name>
  <!-- FIXME change it to the project's website -->
  <url>http://www.example.com</url>

  <properties>
    <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>

  <dependencies>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>4.11</version>
      <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>org.verapdf</groupId>
      <artifactId>validation-model</artifactId>
      <version>1.20.1</version>
    </dependency>
  </dependencies>

  <build>
    <pluginManagement><!-- lock down plugins versions to avoid using Maven defaults (may be moved to parent pom) -->
      <plugins>
        <!-- clean lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#clean_Lifecycle -->
        <plugin>
          <artifactId>maven-clean-plugin</artifactId>
          <version>3.1.0</version>
        </plugin>
        <!-- default lifecycle, jar packaging: see https://maven.apache.org/ref/current/maven-core/default-bindings.html#Plugin_bindings_for_jar_packaging -->
        <plugin>
          <artifactId>maven-resources-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-compiler-plugin</artifactId>
          <version>3.8.0</version>
        </plugin>
        <plugin>
          <artifactId>maven-surefire-plugin</artifactId>
          <version>2.22.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-jar-plugin</artifactId>
          <version>3.0.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-install-plugin</artifactId>
          <version>2.5.2</version>
        </plugin>
        <plugin>
          <artifactId>maven-deploy-plugin</artifactId>
          <version>2.8.2</version>
        </plugin>
        <!-- site lifecycle, see https://maven.apache.org/ref/current/maven-core/lifecycles.html#site_Lifecycle -->
        <plugin>
          <artifactId>maven-site-plugin</artifactId>
          <version>3.7.1</version>
        </plugin>
        <plugin>
          <artifactId>maven-project-info-reports-plugin</artifactId>
          <version>3.0.0</version>
        </plugin>
      </plugins>
    </pluginManagement>
  </build>
</project>
```

And i always get the following error after run (Crtl + F11):
```
Exception in thread "main" java.lang.SecurityException: class "org.verapdf.pdfa.VeraFoundryProvider"'s signer information does not match signer information of other classes in the same package
	at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1151)
	at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:906)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1015)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/jdk.internal.loader.BuiltinClassLoader.defineClass(BuiltinClassLoader.java:800)
	at java.base/jdk.internal.loader.BuiltinClassLoader.findClassOnClassPathOrNull(BuiltinClassLoader.java:698)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClassOrNull(BuiltinClassLoader.java:621)
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:579)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	at org.mrbself.testvera.App.main(App.java:24)
```

The error remains if i switch to older releases (like 1.18.1, 1.18.8, 1.14.0, ..)
Only if i use your last SNAPSHOT the code runs like a charm. I cannot believe, that all releases i tried have really this problem. Especially because the CLI runs in all this versions with any problems in my enviroment. Doing i'm something wrong or miss something? Do you know this problem or can reproduce it and have may be a solution?

Hope for any help.

Lots of compliments and my very best regards,

Thomas

**Comment by thomasgundlach** [comment]
Okaj, i solve it. My local maven repo was the problem. I cloned at beginning the integration branch from github of veraPDF and installed the SNAPSHOT-Versions by maven clean and maven install with eclipse into my local maven repo.
After that i set in the pom of my own maven project dependencies to the release version (1.20.1) of verapdf.
I seems maven had a problem with that and mixed up sources of SNAPSHOT and release version so the run of the code failed into signers errors. after clean up my local maven repo and start direct with the release version 1.20.1 of verapdf (without having verapdf snapshots in my local maven repo) the code runs fine.
i tidy up my local maven repo with follow command in the git bash shell (because i develop on windows os):
```
mvn dependency:purge-local-repository
```
Check, that pom.xml is set to verapdf Version 1.20.1.
Update in Eclipse the Maven Project by Project -> Maven -> Update Project, then Project -> Run As -> Maven clean,  Project -> Run As -> Maven install and run my Code with Eclipse again. Now everything is fine.
