### ISSUE TITLE
Validation fails on NullPointerException

### ISSUE THREAD

**Issue by alisdev** [veraPDF/veraPDF-library#1262]
On a same file:  the first check fails due to NullPointerException, but the second check marks PDF as valid.....

`java.lang.NullPointerException: null
	at org.verapdf.gf.model.impl.pd.GFPDStructElem.getStructureElementStandardType(GFPDStructElem.java:137) ~[validation-model-1.16.1.jar:na]
	at org.verapdf.gf.model.impl.pd.gfse.GFSEGeneral.createTypedStructElem(GFSEGeneral.java:38) ~[validation-model-1.16.1.jar:na]
	at org.verapdf.gf.model.impl.pd.GFPDStructTreeRoot.parseChildren(GFPDStructTreeRoot.java:121) ~[validation-model-1.16.1.jar:na]
	at org.verapdf.gf.model.impl.pd.GFPDStructTreeRoot.getChildren(GFPDStructTreeRoot.java:110) ~[validation-model-1.16.1.jar:na]
	at org.verapdf.gf.model.impl.pd.GFPDStructTreeRoot.getLinkedObjects(GFPDStructTreeRoot.java:100) ~[validation-model-1.16.1.jar:na]
	at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:199) ~[core-1.16.1.jar:na]
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:166) ~[core-1.16.1.jar:na]
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:117) ~[core-1.16.1.jar:na]
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:93) ~[core-1.16.1.jar:na]
	... 144 common frames omitted`

**Comment by MaximPlusov** [comment]
Hello @alisdev. You can try to use the latest release version 1.20.3 https://verapdf.org/software/

**Comment by MaximPlusov** [comment]
I'm not sure. If that doesn't help, could you share with us the file that's causing this error?

**Comment by MaximPlusov** [comment]
I guess we have some mismatch with last version number (veraPDF v1.20.2 Version 1.20.3), but this is the correct link

**Comment by alisdev** [comment]
Hi, I can see that the version is correct now, when will be deployed in the maven repository, please?

**Comment by MaximPlusov** [comment]
Hi. It's already should be deployed in the maven repository.
