### ISSUE TITLE
Deploy 1.20.3 on Maven Central

### ISSUE THREAD

**Issue by bsanchezb** [veraPDF/veraPDF-library#1279]
Hello,

I have a problem with the current Maven release 1.20.2 of [validation-model](https://mvnrepository.com/artifact/org.verapdf/validation-model) artifact. As the required transitive dependency [core](https://mvnrepository.com/artifact/org.verapdf/core) has been published only with the version 1.20.1, when building my project I get the following exception:
```
java.lang.ExceptionInInitializerError
        at eu.europa.esig.dss.pdfa.PDFAStructureValidatorTest.<clinit>(PDFAStructureValidatorTest.java:13)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized0(Native Method)
        at java.base/jdk.internal.misc.Unsafe.ensureClassInitialized(Unsafe.java:1160)
...
Caused by: java.lang.SecurityException: class "org.verapdf.pdfa.VeraFoundryProvider"'s signer information does not match signer information of other classes in the same package
        at java.base/java.lang.ClassLoader.checkCerts(ClassLoader.java:1159)
        at java.base/java.lang.ClassLoader.preDefineClass(ClassLoader.java:903)
        at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1011)
        at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150)
...
```

I think the problem is that the verapdf module versions are not synchronized with each other on Maven Central.

Would it be possible to deploy the latest available version of VeraPdf on Maven Central for all available modules?

Thank you in advance.

Best regards,
Aleksandr.

**Comment by carlwilson** [comment]
Thanks for reporting this @bsanchezb I've just published the missing artefacts I believe. It might take 48 hours before they are properly indexed and available on Maven central. Let me know to confirm that this is fixed, please. Thanks, Carl.

**Comment by bdoubrov** [comment]
@bsanchezb just to let you know, the new release 1.22 was published yesterday. Feel free to upgrade to it instead

**Comment by bsanchezb** [comment]
@carlwilson , @bdoubrov , that is very good news! 1.22.2 is even better! I have tested the artifacts from Maven Central and everything works fine now!

I will close the ticket.

Best regards,
Aleksandr.
