### ISSUE TITLE
java.io.IOException: Invalid sequence tag in DER

### ISSUE THREAD

**Issue by a20dev** [veraPDF/veraPDF-library#1305]
[orange.pdf](https://github.com/veraPDF/veraPDF-library/files/10012836/orange.pdf)

veraPDF 1.22.3 throws this exception for the attached document:

java.io.IOException: Invalid sequence tag in DER
        at org.verapdf.pdfa.parsers.pkcs7.PKCS7.parse(PKCS7.java:67)
        at org.verapdf.pdfa.parsers.pkcs7.PKCS7.<init>(PKCS7.java:39)
        at org.verapdf.gf.model.impl.external.GFPKCSDataObject.<init>(GFPKCSDataObject.java:54)
        at org.verapdf.gf.model.impl.pd.signature.GFPDSignature.getContents(GFPDSignature.java:86)
        at org.verapdf.gf.model.impl.pd.signature.GFPDSignature.getLinkedObjects(GFPDSignature.java:72)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:213)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:180)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:130)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:106)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:244)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:122)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:122)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:77)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFilePaths(VeraPdfCliProcessor.java:172)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:133)
        at org.verapdf.cli.VeraPdfCli.singleThreadProcess(VeraPdfCli.java:140)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:108)
        at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:54)
Caused by: java.io.IOException: Invalid sequence tag in DER
        at org.verapdf.pdfa.parsers.pkcs7.DEREncodedInputStream.getSequence(DEREncodedInputStream.java:99)
        at org.verapdf.pdfa.parsers.pkcs7.PKCS7$ContentInfo.<init>(PKCS7.java:155)
        at org.verapdf.pdfa.parsers.pkcs7.PKCS7.parse(PKCS7.java:73)
        at org.verapdf.pdfa.parsers.pkcs7.PKCS7.parse(PKCS7.java:61)
        ... 18 more

To me (and Adobe Acrobat), the signature looks OK.

**Comment by a20dev** [comment]
SubFilter is adbe.x509.rsa_sha1 (deprecated in PDF 2.0), therefore Contents must be an OCTET STRING. Note that orange.pdf is a PDF 1.4 document claiming to conform to PDF/A-1b rather than PDF/A-2.

Curiously, annex B.1 of ISO 19905-2 first requires Contents to be a PKCS #7 object and then relaxes that requirement in NOTE 3. Perhaps that contradiction merits its own bug report over at pdf-issues.

**Comment by bdoubrov** [comment]
We've changed the level of the log message from WARNING to INFO when we encounter the ASN.1 OCTET STRING type in the /Contents entry. This fix is already available in the latest dev build 1.23.91

**Comment by MaximPlusov** [comment]
Included into release 1.24
