### ISSUE TITLE
Output doesn't contain info on exception for PDF with leading junk bytes

### ISSUE THREAD

**Issue by bitsgalore** [veraPDF/veraPDF-library#1340]
The leading 128 bytes of this file (before the PDF header) contain junk:

[CERN-2005-009.pdf](https://wiki.opf-labs.org/download/attachments/101613571/CERN-2005-009.pdf?version=1&modificationDate=1472125536000)

I ran VeraPDF on it using:

```
verapdf --off --extract CERN-2005-009.pdf > CERN-2005-009-vera.xml
```
This results in an exception (most likely because of the junk bytes) that is written to stderr:

```
WARNING: IO error while trying to find first document dictionary
java.io.IOException: Unknown symbol 32 after '>'
	at org.verapdf.parser.BaseParser.nextToken(BaseParser.java:203)
	at org.verapdf.parser.BaseParser.findKeyword(BaseParser.java:161)
	at org.verapdf.parser.PDFParser.findFirstDictionary(PDFParser.java:179)
	at org.verapdf.parser.PDFParser.isLinearized(PDFParser.java:160)
	at org.verapdf.io.Reader.isLinearized(Reader.java:129)
	at org.verapdf.cos.COSDocument.initCOSDocument(COSDocument.java:114)
	at org.verapdf.cos.COSDocument.<init>(COSDocument.java:94)
	at org.verapdf.pd.PDDocument.<init>(PDDocument.java:67)
	at org.verapdf.gf.model.GFModelParser.<init>(GFModelParser.java:96)
	at org.verapdf.gf.model.GFModelParser.createModelWithFlavour(GFModelParser.java:130)
	at org.verapdf.gf.foundry.VeraFoundry.createParser(VeraFoundry.java:90)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:116)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:122)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:77)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.cli.VeraPdfCliProcessor.processFilePaths(VeraPdfCliProcessor.java:172)
	at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:133)
	at org.verapdf.cli.VeraPdfCli.singleThreadProcess(VeraPdfCli.java:140)
	at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:108)
	at org.verapdf.apps.GreenfieldCliWrapper.main(GreenfieldCliWrapper.java:54)
```
The [output file](https://github.com/KBNLresearch/pdf-characterisation/blob/main/output/jhove-pdfhul-impact/pdf-hul-137/CERN-2005-009-vera.xml) doesn't contain any reference to the exception: there's no *taskResult* element, and the value of *veraExceptions* in the *batchSummary* element is 0:

```xml
  <batchSummary totalJobs="1" failedToParse="0" encrypted="0" outOfMemory="0" veraExceptions="0">
    <validationReports compliant="0" nonCompliant="0" failedJobs="0">0</validationReports>
    <featureReports failedJobs="0">1</featureReports>
    <repairReports failedJobs="0">0</repairReports>
    <duration start="1685543702228" finish="1685543702705">00:00:00.477</duration>
  </batchSummary>
```
I'm not exactly sure what error level is needed to raise *veraExceptions* (after all, the exception is only a warning). Still, the presence of junk bytes could result in unpredictable viewer behavior, so it might be helpful to include some reference to this exception in VeraPDF's output, if only to alert the user something odd is going on with this file.

VeraPDF version used: 1.22.3

**Comment by bdoubrov** [comment]
@bitsgalore logs are not added to the report by default. This has to be enabled by the addtional CLI argument `--addlogs`. So, I believe this command line should work:
```
verapdf --off --addlogs --extract CERN-2005-009.pdf > CERN-2005-009-vera.xml
```

**Comment by bitsgalore** [comment]
@bdoubrov Yes, adding `--addlogs` did the trick (wasn't aware of that option), thanks!
