### ISSUE TITLE
ModelParsingException: Couldn't parse stream - startxref validation failed

### ISSUE THREAD

**Issue by Samyssmile** [veraPDF/veraPDF-library#1498]
Inputfile: [5LJK3WBGEWURVXHBKF7FQP32FD7C7FQO.pdf](https://github.com/user-attachments/files/18270849/5LJK3WBGEWURVXHBKF7FQP32FD7C7FQO.pdf)

My Code

```
            VeraGreenfieldFoundryProvider.initialise();
            PDFAFlavour flavour = PDFAFlavour.PDFUA_2;
            Set<TranslationEntity> translations = new HashSet<>();
            try (VeraPDFFoundry foundry = Foundries.defaultInstance(); PDFAParser parser = foundry.createParser(file, flavour)) 
```
**It fails on: createParser**

### Exception
`
org.verapdf.core.ModelParsingException: Couldn't parse stream
Caused by: java.io.IOException: startxref validation failed
	at org.verapdf.parser.PDFParser.getXRefInfo(PDFParser.java:567)
	at org.verapdf.parser.PDFParser.getXRefInfo(PDFParser.java:241)
	at org.verapdf.io.Reader.init(Reader.java:152)
	at org.verapdf.io.Reader.<init>(Reader.java:59)
	at org.verapdf.cos.COSDocument.initReader(COSDocument.java:126)
	at org.verapdf.cos.COSDocument.<init>(COSDocument.java:93)
	at org.verapdf.pd.PDDocument.<init>(PDDocument.java:67)
	at org.verapdf.gf.model.GFModelParser.<init>(GFModelParser.java:92)
	at org.verapdf.gf.model.GFModelParser.createModelWithFlavour(GFModelParser.java:152)
	`
	
### Used
```
implementation 'org.verapdf:core-jakarta:1.26.2'
implementation 'org.verapdf:validation-model-jakarta:1.26.2'
```

**Comment by bdoubrov** [comment]
@Samyssmile the issue is caused by a 40,000+ NULL characters after `%%EOF` marker at the end of PDF file. veraPDF currently looks for `%%EOF` marker in the last 1024 bytes of the source file, and naturally fails in this case. 

I see you are specifying the validation profile as PDF/UA-2, which is based on ISO 32000-2 (PDF 2.0). The latter specification says that (7.5.5 File trailer)

> The last line of the file shall contain only the end-of-file marker, %%EOF.

So, I'd say that veraPDF's parser error `startxref validation failed` is correct.
