### ISSUE TITLE
veraPDF command line parameter parsing failure should be handled gracefully

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-library#449]
When using the CLI version of VeraPDF 0.8.7 with a wrong parameter this stack trace is thrown: 

    $ ./verapdf --passsdfdsf
    
    log4j:ERROR Could not find value for key log4j.appender.file
    log4j:ERROR Could not instantiate appender named "file".
    10:44:39,279 FATAL main VeraPdfCli:logThrowable:80 - Unknown option: --passsdfdsf
    com.beust.jcommander.ParameterException: Unknown option: --passsdfdsf
	    at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
	    at com.beust.jcommander.JCommander.parse(JCommander.java:282)
	    at com.beust.jcommander.JCommander.parse(JCommander.java:265)
	    at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:49)

**Comment by carlwilson** [comment]
Closed by #478.
