### ISSUE TITLE
XmpParsingException resulting in "PDF file is not compliant with Validation Profile requirements"

### ISSUE THREAD

**Issue by kriegaex** [veraPDF/veraPDF-library#496]
If I open certain PDFs, trying to validate them against PDF/A-1a or 1b profiles, I get an error in the GUI: "PDF file is not compliant with Validation Profile requirements"

Simultaneously the console says:

```
10:20:11,045 ERROR SwingWorker-pool-2-thread-1 XMPChecker:doesInfoMatchXMP:93 - Problems with XMP parsing. Missing pdfaSchema:property in type definition
org.apache.xmpbox.xml.XmpParsingException: Missing pdfaSchema:property in type definition
        at org.apache.xmpbox.xml.PdfaExtensionHelper.populatePDFASchemaType(PdfaExtensionHelper.java:152)
        at org.apache.xmpbox.xml.PdfaExtensionHelper.populateSchemaMapping(PdfaExtensionHelper.java:116)
        at org.apache.xmpbox.xml.DomXmpParser.parse(DomXmpParser.java:169)
        at org.verapdf.model.tools.XMPChecker.doesInfoMatchXMP(XMPChecker.java:74)
        at org.verapdf.model.impl.pb.cos.PBCosDocument.<init>(PBCosDocument.java:101)
        at org.verapdf.model.impl.pb.cos.PBCosDocument.<init>(PBCosDocument.java:63)
        at org.verapdf.model.ModelParser.getRoot(ModelParser.java:59)
        at org.verapdf.pdfa.validators.BaseValidator.validate(BaseValidator.java:371)
        at org.verapdf.gui.ValidateWorker.runValidator(ValidateWorker.java:171)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:95)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:46)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
10:20:15,904 ERROR SwingWorker-pool-2-thread-1 PBoxPDMetadata:getXMPPackage:80 - Problems with parsing metadata. Missing pdfaSchema:property in type definition
org.apache.xmpbox.xml.XmpParsingException: Missing pdfaSchema:property in type definition
        at org.apache.xmpbox.xml.PdfaExtensionHelper.populatePDFASchemaType(PdfaExtensionHelper.java:152)
        at org.apache.xmpbox.xml.PdfaExtensionHelper.populateSchemaMapping(PdfaExtensionHelper.java:116)
        at org.apache.xmpbox.xml.DomXmpParser.parse(DomXmpParser.java:169)
        at org.verapdf.model.impl.pb.pd.PBoxPDMetadata.getXMPPackage(PBoxPDMetadata.java:74)
        at org.verapdf.model.impl.pb.pd.PBoxPDMetadata.getLinkedObjects(PBoxPDMetadata.java:59)
        at org.verapdf.pdfa.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:194)
        at org.verapdf.pdfa.validators.BaseValidator.checkNext(BaseValidator.java:136)
        at org.verapdf.pdfa.validators.BaseValidator.validate(BaseValidator.java:87)
        at org.verapdf.pdfa.validators.BaseValidator.validate(BaseValidator.java:371)
        at org.verapdf.gui.ValidateWorker.runValidator(ValidateWorker.java:171)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:95)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:46)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)
```

The document can be viewed in Acrobat Reader or in Chrome's built-in PDF viewer.

**Comment by carlwilson** [comment]
Hi @kriegaex 

We're very close to a new release. One of the key features is the replacement of the current XMP Box metadata library to fix some XMP problems. Would you mind downloading our latest [development installer](http://downloads.verapdf.org/dev/verapdf-installer.zip), which will be 0.9.35 or higher, repeating the validtion and letting us know the results?

Thanks very much

**Comment by kriegaex** [comment]
Yes, now I can validate the document (it does not conform to PDF/A, as expected) and get the expected HTML or XML report. Thanks for the quick reaction.

**Comment by carlwilson** [comment]
To be honest the quick response was helped by the issue coming at a convenient time as we were just finishing the next release. I'll close this issue, if you're interested v0.10.1 will be available on Monday.

**Comment by kriegaex** [comment]
Today I am seeing new versions 0.10.2, 0.10.3 and 0.10.5 on your download server. Have you had problems with the release and pushed some hotfixes? Should I wait a little longer or is the current version stable?
