### ISSUE TITLE
No CLI parameters causes null pointer exception.

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-library#63]
After building and moving to the `cli/target` directory and executing the jar without parameters, e.g.
```
java -jar vera-cli-1.0-SNAPSHOT-jar-with-dependencies.jar 
```
I get the following exception:
```
Exception in thread "main" java.lang.NullPointerException
        at java.io.File.<init>(File.java:277)
        at org.verapdf.model.ModelLoader.getRoot(ModelLoader.java:29)
        at org.verapdf.runner.ValidationRunner.runValidation(ValidationRunner.java:31)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:36)
```
This should really return a help message.

**Comment by carlwilson** [comment]
Fixed
