### ISSUE TITLE
No help option for the command line application

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-library#64]
After building and moving to the `cli/target` directory and executing the jar with a --help parameters, e.g.
```
java -jar vera-cli-1.0-SNAPSHOT-jar-with-dependencies.jar --help
```
I get the following exception:
```
Exception in thread "main" com.beust.jcommander.ParameterException: Unknown option: --help
        at com.beust.jcommander.JCommander.parseValues(JCommander.java:742)
        at com.beust.jcommander.JCommander.parse(JCommander.java:282)
        at com.beust.jcommander.JCommander.parse(JCommander.java:265)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:32)
```
This should return a standard help message, related to #63 as no parameters should issue the same help message.

**Comment by carlwilson** [comment]
fixed in 0.7
