### ISSUE TITLE
Maven build instructions on front page fail when building from scratch.

### ISSUE THREAD

**Issue by ravn** [veraPDF/veraPDF-library#669]
Following the build instructions to the letter for the "master" branch with an unpopulated local ~/.m2 repository results in the following error:

[ERROR] Failed to execute goal on project core: Could not resolve dependencies for project org.verapdf:core:jar:0.8.0: Failed to collect dependencies for [org.verapdf:pdf-model:jar:[0.8.0,0.9.0) (compile), rhino:js:jar:1.7R2 (compile), junit:junit:jar:4.12 (compile), nl.jqno.equalsverifier:equalsverifier:jar:1.5.1 (test)]: No versions available for org.verapdf:pdf-model:jar:[0.8.0,0.9.0) within specified range -> [Help 1]

Perhaps the prerequisites need to include building the needed verapdf artifacts?

**Comment by jonasstein** [comment]
confirmed here.
```
cd /tmp ; wget https://github.com/veraPDF/veraPDF-library/archive/master.tar.gz
tar xvf master.tar.gz
mvn clean install  -P clone-test-resources
```
failed on Gentoo Linux with Maven 3.3.3 too.

**Comment by carlwilson** [comment]
Master is now up to date and I've checked the build instructions and believe they're now fine.

**Comment by jonasstein** [comment]
the README suggests now to check out master and run `mvn clean install`
Compilation ends with no Error message and looks fine to me, but
I can not start the application.

```
$ mvn --version
Apache Maven 3.3.3 (7994120775791599e205a5524ec3e0dfe41d4a06; 2015-04-22T13:57:37+02:00)
Maven home: /usr/share/maven-bin-3.3
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /opt/oracle-jdk-bin-1.8.0.144/jre
Default locale: en_GB, platform encoding: UTF-8
OS name: "linux", version: "4.9.34-gentoo+", arch: "amd64", family: "unix"


java -jar ~/.m2/repository/org/verapdf/core/1.8.0/core-1.8.0.jar 
no main manifest attribute, in /home/stein/.m2/repository/org/verapdf/core/1.8.0/core-1.8.0.jar
```

**Comment by csinowski** [comment]
Hello,
I am also trying to work with the library and everytime I run `mvn clean install` I get issues with dependencies.

`mvn --version`
Maven 3.6.0 & Java 1.8.0_201

Non-resolvable parent POM for org.verapdf:verapdf-library:1.14.0: Could not find artifact

Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project navigator-sdk-examples: Compilation failure

So I decided to add 
```
       <version>3.6.0</version>
            <configuration>
                <source>1.8</source>
                <target>1.8</target>
            </configuration>
```

This continues with dependencies of core and pdf-model, which could not be found in 

_maven-metadata-central.xml_

so I thought of changing the pom.xml by removing -SNAPSHOT from the version and replacing it with the latest `<release>` version without success. 

Any recommendations?

**Comment by bdoubrov** [comment]
The README is updated and contains the correct build instructions

**Comment by knoami** [comment]
I just try to install it and I got the following:

`[ERROR] Tests run: 17, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.006 s <<< FAILURE! -- in org.verapdf.version.SemanticVersionTest
[ERROR] org.verapdf.version.SemanticVersionTest.testGetVersionString -- Time elapsed: 0.003 s <<< FAILURE!
org.junit.ComparisonFailure: expected:<[1.0.0]> but was:<[?.?.?]>
        at org.junit.Assert.assertEquals(Assert.java:117)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at org.verapdf.version.SemanticVersionTest.testGetVersionString(SemanticVersionTest.java:168)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
        at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
        at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
        at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:316)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:240)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:214)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:155)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:385)
        at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:162)
        at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:507)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:495)

[INFO]
[INFO] Results:
[INFO]
[ERROR] Failures:
[ERROR]   AuditDurationImplTest.testGetStringDuration:47 expected:<[00:00:00.000]> but was:<[??:??:??.???]>
[ERROR]   SemanticVersionTest.testGetVersionString:168 expected:<[1.0.0]> but was:<[?.?.?]>
[INFO]
[ERROR] Tests run: 290, Failures: 2, Errors: 0, Skipped: 0
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for veraPDF PDF/A Validation Library 1.26.0:
[INFO]
[INFO] veraPDF PDF/A Validation Library ................... SUCCESS [  ?.??? s]
[INFO] veraPDF PDF/A XMP Library Core ..................... SUCCESS [  ?.??? s]
[INFO] veraPDF Library core ............................... FAILURE [  ?.??? s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  ??.??? s
[INFO] Finished at: ????-??-??T??:??:??+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:3.2.5:test (default-test) on project core:
 There are test failures.
[ERROR]
[ERROR] Please refer to D:\Java\veraPDF-library\core\target\surefire-reports for the individual test results.
[ERROR] Please refer to dump files (if any exist) [date].dump, [date]-jvmRun[N].dump and [date].dumpstream.
[ERROR] -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR]
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :core`

**Comment by ravn** [comment]
@knoami please create a new issue instead of commenting on an old, closed one.

**Comment by knoami** [comment]
Okay, sorry for that
