### ISSUE TITLE
Command line reporting on exception

### ISSUE THREAD

**Issue by prwheatley** [veraPDF/veraPDF-library#670]
Previous issues I had with crashes to the command line now appear to be fixed in v0.28, and the few exceptions I do have now seem to occur in a much more graceful manner and as they should, with one minor outstanding issue. In this case, an exception results in this message on the command line (DOS):

```
WARNING: OutOfMemory caught when validaing item
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOf(Unknown Source)
        at java.lang.AbstractStringBuilder.expandCapacity(Unknown Source)
        at java.lang.AbstractStringBuilder.ensureCapacityInternal(Unknown Source)
        at java.lang.AbstractStringBuilder.append(Unknown Source)
        at java.lang.StringBuilder.append(Unknown Source)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:232)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:165)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:116)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:87)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:176)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:119)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:98)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:75)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:63)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:61)
        at org.verapdf.processor.BatchFileProcessor.processContainer(BatchFileProcessor.java:38)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:73)
        at org.verapdf.cli.VeraPdfCliProcessor.processBatch(VeraPdfCliProcessor.java:158)
        at org.verapdf.cli.VeraPdfCliProcessor.processDir(VeraPdfCliProcessor.java:121)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:100)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:79)
```

It would be helpful if this message included the path of the current file being validated, and I'm guessing that's possibly what's meant to happen on the first line of this message above? This message seems to match up with an exception reported in the XML output, but without the name/path it's difficult to verify. Also note the spelling error in the word "validating".

**Comment by prwheatley** [comment]
Following on from the issue above, I thought I'd go back and look at the error and warning reporting on another test corpus (the one sourced from the UK Web Archive which has some broken files).

This is what appeared on the DOS command line running v0.28.4:

```
D:\Data>verapdf -x -r testcorpora\UKWA > ukwa.xml
Dec 22, 2016 5:37:57 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1as_UKWA\appform_personal.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 5:43:34 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1as_UKWA\contactsa.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 5:52:57 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1as_UKWA\Enrolment.form.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 5:58:21 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1as_UKWA\June_2008_Newsletter.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:12:11 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1as_UKWA\TCS2008cfp-1.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:13:52 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\1.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:13:52 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-07-02T13:12:00Z:T  is not a valid ISO8601 date value
Dec 22, 2016 6:13:53 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-05-02T10:09:09Z:ml is not a valid ISO8601 date value
Dec 22, 2016 6:15:06 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\55no2synopsis.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:15:25 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-28T10:07:03Z:sl is not a valid ISO8601 date value
Dec 22, 2016 6:15:26 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-28T11:36:33Z:ti is not a valid ISO8601 date value
Dec 22, 2016 6:15:26 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-28T11:37:48Z:ti is not a valid ISO8601 date value
Dec 22, 2016 6:15:27 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-28T11:38:19Z:ti is not a valid ISO8601 date value
Dec 22, 2016 6:15:27 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-28T11:38:31Z:ti is not a valid ISO8601 date value
Dec 22, 2016 6:15:28 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-28T11:38:42Z:ti is not a valid ISO8601 date value
Dec 22, 2016 6:15:32 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-06-26T15:38:23Z:ia is not a valid ISO8601 date value
Dec 22, 2016 6:15:37 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-07-02T09:39:13Z: c is not a valid ISO8601 date value
Dec 22, 2016 6:15:42 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-05-13T12:09:15Z:Ar is not a valid ISO8601 date value
Dec 22, 2016 6:16:13 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\Completescopingrequest.pdf doesn't appear to be a valid PDF.
18:16:15,633 ERROR main ModelParser:obtainFlavour:83 - com.adobe.xmp.XMPException: XML parsing failure
[Fatal Error] :6:24: The entity name must immediately follow the '&' in the entity reference.
Dec 22, 2016 6:16:15 PM org.verapdf.report.FeaturesNode fromValues
INFO: The entity name must immediately follow the '&' in the entity reference.
org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 24; The entity name must immediately follow the '&' in the entity reference.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.verapdf.report.XmpHandler.parseMetadataRootElement(XmpHandler.java:120)
        at org.verapdf.report.FeaturesNode.fromXmp(FeaturesNode.java:172)
        at org.verapdf.report.FeaturesNode.fromValues(FeaturesNode.java:112)
        at org.verapdf.report.FeaturesNode.fromValues(FeaturesNode.java:127)
        at org.verapdf.report.FeaturesReport.getFirstNodeFromType(FeaturesReport.java:114)
        at org.verapdf.report.FeaturesReport.fromValues(FeaturesReport.java:94)
        at org.verapdf.processor.ProcessorResultImpl.getFeaturesReport(ProcessorResultImpl.java:132)
        at org.verapdf.processor.AbstractBatchHandler.processTasks(AbstractBatchHandler.java:60)
        at org.verapdf.processor.AbstractBatchHandler.handleResult(AbstractBatchHandler.java:32)
        at org.verapdf.processor.AbstractBatchProcessor.processResult(AbstractBatchProcessor.java:96)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:76)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:63)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:61)
        at org.verapdf.processor.BatchFileProcessor.processContainer(BatchFileProcessor.java:38)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:73)
        at org.verapdf.cli.VeraPdfCliProcessor.processBatch(VeraPdfCliProcessor.java:158)
        at org.verapdf.cli.VeraPdfCliProcessor.processDir(VeraPdfCliProcessor.java:121)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:100)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:79)

Dec 22, 2016 6:17:18 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-05-08T09:38:29Z:aw is not a valid ISO8601 date value
Dec 22, 2016 6:17:52 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\empty_homes_strategy_07_web_v2.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:17:55 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\erscb_procedures_guidance.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:19:56 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\Guild_Membership_Renewal_2007.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:20:01 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\Hybrids_Report.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:24:59 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\pr08-dft_determin-price_list.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:25:21 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\Promptsheet.pdf doesn't appear to be a valid PDF.
Dec 22, 2016 6:25:47 PM org.verapdf.processor.ProcessorImpl process
WARNING: D:\Data\testcorpora\UKWA\1bs_UKWA\savingsdirectdebit.pdf doesn't appear to be a valid PDF.
18:26:27,640 ERROR main ModelParser:obtainFlavour:83 - com.adobe.xmp.XMPException: XML parsing failure
[Fatal Error] :6:22: The entity name must immediately follow the '&' in the entity reference.
Dec 22, 2016 6:26:31 PM org.verapdf.report.FeaturesNode fromValues
INFO: The entity name must immediately follow the '&' in the entity reference.
org.xml.sax.SAXParseException; lineNumber: 6; columnNumber: 22; The entity name must immediately follow the '&' in the entity reference.
        at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(Unknown Source)
        at org.verapdf.report.XmpHandler.parseMetadataRootElement(XmpHandler.java:120)
        at org.verapdf.report.FeaturesNode.fromXmp(FeaturesNode.java:172)
        at org.verapdf.report.FeaturesNode.fromValues(FeaturesNode.java:112)
        at org.verapdf.report.FeaturesNode.fromValues(FeaturesNode.java:127)
        at org.verapdf.report.FeaturesReport.getFirstNodeFromType(FeaturesReport.java:114)
        at org.verapdf.report.FeaturesReport.fromValues(FeaturesReport.java:94)
        at org.verapdf.processor.ProcessorResultImpl.getFeaturesReport(ProcessorResultImpl.java:132)
        at org.verapdf.processor.AbstractBatchHandler.processTasks(AbstractBatchHandler.java:60)
        at org.verapdf.processor.AbstractBatchHandler.handleResult(AbstractBatchHandler.java:32)
        at org.verapdf.processor.AbstractBatchProcessor.processResult(AbstractBatchProcessor.java:96)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:76)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:63)
        at org.verapdf.processor.BatchFileProcessor.processDir(BatchFileProcessor.java:61)
        at org.verapdf.processor.BatchFileProcessor.processContainer(BatchFileProcessor.java:38)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:73)
        at org.verapdf.cli.VeraPdfCliProcessor.processBatch(VeraPdfCliProcessor.java:158)
        at org.verapdf.cli.VeraPdfCliProcessor.processDir(VeraPdfCliProcessor.java:121)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:100)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:79)

Dec 22, 2016 6:27:20 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-06-24T15:02:39Z:pa is not a valid ISO8601 date value
Dec 22, 2016 6:27:21 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-06-17T12:36:13Z:pa is not a valid ISO8601 date value
Dec 22, 2016 6:27:33 PM org.verapdf.model.tools.xmp.validators.DateTypeValidator isCorresponding
WARNING: Node:CreateDate with value:2008-04-04T12:14:09Z: K is not a valid ISO8601 date value
```

And this is the key contents of the corresponding exception report in the output xml where the exception report was labelled with an "isSuccess=false":

```
D:\Data\testcorpora\UKWA\1as_UKWA\appform_personal.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1as_UKWA\contactsa.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1as_UKWA\Enrolment.form.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1as_UKWA\June_2008_Newsletter.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1as_UKWA\TCS2008cfp-1.pdf	 Exception: Couldn't parse stream caused by exception: Error: End-of-File expected line
D:\Data\testcorpora\UKWA\1bs_UKWA\1.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\55no2synopsis.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\Completescopingrequest.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\empty_homes_strategy_07_web_v2.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\erscb_procedures_guidance.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\Guild_Membership_Renewal_2007.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\Hybrids_Report.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\pr08-dft_determin-price_list.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\Promptsheet.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
D:\Data\testcorpora\UKWA\1bs_UKWA\savingsdirectdebit.pdf	 Exception: Couldn't parse stream caused by exception: Document doesn't contain startxref keyword
```

It's worth noting that all of these were truncated files (but from a quick inspection look like reasonable PDFs as far as they go) except for "TCS2008cfp-1.pdf" which was actually an HTML file with the wrong file extension. It's also worth noting that they all match up - each command line warning/error corresponds with an exception reported in the XML. All well and good.

But nosing around in the reporting and thinking about it's implications raised a point for further discussion, and a very minor reporting error:

1) Firstly, why the inconsistency between the warnings/errors and the exception reporting in the XML? It seems understandable that the exception report should state the exact issue encountered, although it's actually less detailed than the command line warning/error. But the command line message also adds an interpretation of this ("this does not appear to be a valid PDF"), and perhaps one that could benefit from being in the exception report - as it's a useful one. The progression of this thinking is how really significant problems (i.e. beyond specific PDF/A compliance issues) are identified and reported. In this case, veraPDF is managing to identify truncated files - suggesting that a previous process has malfunctioned in some way. This is an incredibly useful result in a digital preservation context - it triggers the alarm to investigate what has gone wrong in the previous workflow and hopefully step back and find a copy of the original file before it was truncated.

So... is there some further testing to do around damaged files and perhaps some further consideration of how veraPDF can identify these and best report them?

2) The TCS2008cfp-1.pdf exception report seems to be missing the line number, although if the eof is missing this is somewhat nonsensical.

**Comment by david-russo** [comment]
To add to the original issue: the same "validaing" message has been copied without modification to also log [feature](https://github.com/veraPDF/veraPDF-library/blob/f381598b05dc9e05ac30a784bd7dfcff1fd3727a/core/src/main/java/org/verapdf/processor/ProcessorImpl.java#L253) [extraction](https://github.com/veraPDF/veraPDF-library/blob/f381598b05dc9e05ac30a784bd7dfcff1fd3727a/core/src/main/java/org/verapdf/processor/ProcessorImpl.java#L254) and [metadata](https://github.com/veraPDF/veraPDF-library/blob/f381598b05dc9e05ac30a784bd7dfcff1fd3727a/core/src/main/java/org/verapdf/processor/ProcessorImpl.java#L228) [correction](https://github.com/veraPDF/veraPDF-library/blob/f381598b05dc9e05ac30a784bd7dfcff1fd3727a/core/src/main/java/org/verapdf/processor/ProcessorImpl.java#L229) failures, so those also need to be corrected and amended to include some form of file identifier, along with any other messages reported during processing.

Are there perhaps some information-level logs that could already tell us which item is being processed? If so, an option for increasing log verbosity seems like it could be beneficial when we find error messages lacking in the future.

**Comment by carlwilson** [comment]
We've reviewed this and it covers a fair bit of ground across controlling application output, logging and the difference between helpful app messages and Java stack traces. We've decided that we'll draft a 1 pager suggesting how we'll handle these going forward, review this with @david-russo  and @prwheatley before implementing in 1.6.
