### ISSUE TITLE
Greenfield parser crash

### ISSUE THREAD

**Issue by stanislav-rogozhin** [veraPDF/veraPDF-library#677]
Greenfield parser crashes when validating attached file
[pdfa_NA60.pdf](https://github.com/veraPDF/veraPDF-library/files/702119/pdfa_NA60.pdf)

WARNING: Exception caught when validaing item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:109)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:196)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:139)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:118)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:95)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:71)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFiles(VeraPdfCliProcessor.java:152)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:126)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:100)
Caused by: java.lang.ArrayIndexOutOfBoundsException: -115
        at org.verapdf.pd.font.Encoding.getName(Encoding.java:92)
        at org.verapdf.gf.model.tools.TransparencyBehaviour.fontCheck(TransparencyBehaviour.java:174)
        at org.verapdf.gf.model.tools.TransparencyBehaviour.containsTransparency(TransparencyBehaviour.java:158)

This file is not a valid PDF/A, however other applications and PDFBox version only report validation errors.

**Comment by BezrukovM** [comment]
fixed by https://github.com/veraPDF/veraPDF-parser/pull/175
