### ISSUE TITLE
RuntimeException when validating file after metadata fixing

### ISSUE THREAD

**Issue by nunovieira220** [veraPDF/veraPDF-library#680]
After executing a metadata fixing on this [pdf](https://publications.europa.eu/pt/publication-detail/-/publication/1d77ce47-3dfa-4fb9-ac27-223975ce3795), we tried to validate it, all via GUI (v1.0.5). It throwed a runtime exception (with the following stack trace) and the final report was empty.

```
WARNING: Exception caught when validaing item
org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:109)
	at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:196)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:139)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:118)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:95)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:71)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:101)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:48)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.RuntimeException: Error while parsing object : 112 0
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1773)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
	at org.mozilla.javascript.gen.c94._c0(unnamed script:0)
	at org.mozilla.javascript.gen.c94.call(unnamed script)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c94.call(unnamed script)
	at org.mozilla.javascript.gen.c94.exec(unnamed script)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkObjWithRule(BaseValidator.java:372)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkAllRules(BaseValidator.java:295)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:181)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:136)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:107)
	... 14 more
Caused by: java.lang.RuntimeException: Error while parsing object : 112 0
	at org.verapdf.cos.COSDocument.getObject(COSDocument.java:224)
	at org.verapdf.cos.COSIndirect.getDirect(COSIndirect.java:368)
	at org.verapdf.cos.COSIndirect.getType(COSIndirect.java:80)
	at org.verapdf.cos.COSObject.getType(COSObject.java:98)
	at org.verapdf.gf.model.impl.pd.util.XMPChecker.getInformationDictionary(XMPChecker.java:118)
	at org.verapdf.gf.model.impl.pd.util.XMPChecker.doesInfoMatchXMP(XMPChecker.java:76)
	at org.verapdf.gf.model.impl.cos.GFCosDocument.getdoesInfoMatchXMP(GFCosDocument.java:215)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
	... 27 more
Caused by: java.io.IOException: Seeking can't be performed; stream is closed
	at org.verapdf.io.InternalInputStream.checkClosed(InternalInputStream.java:223)
	at org.verapdf.io.InternalInputStream.seek(InternalInputStream.java:139)
	at org.verapdf.parser.PDFParser.getObject(PDFParser.java:226)
	at org.verapdf.io.Reader.getObject(Reader.java:113)
	at org.verapdf.io.Reader.getObject(Reader.java:86)
	at org.verapdf.cos.COSDocument.getObject(COSDocument.java:216)
	... 38 more
```

**Comment by shem-sergey** [comment]
Fixed in https://github.com/veraPDF/veraPDF-parser/pull/176.
