### ISSUE TITLE
Exception when enabling Plugins: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by ilcapitanomark** [veraPDF/veraPDF-library#704]
Hi, 
in order to understand how the plugins are working, I've downloaded and installed verapdf-1.0.12-PDFBOX.
Then I ran without plugins and I succeeded
Finally I I've enabled individually the Plugins with the config file, ran again and I got:

Feb 06, 2017 4:00:34 PM org.verapdf.processor.ProcessorImpl extractFeatures
WARNING: Exception caught when extracting features of item
java.lang.NoSuchMethodError: org.verapdf.features.FontFeaturesData.getStream()[B
	at org.verapdf.FontSampleExtractor.getFontFeatures(FontSampleExtractor.java:26)
	at org.verapdf.features.AbstractFontFeaturesExtractor.getFeatures(AbstractFontFeaturesExtractor.java:40)
	at org.verapdf.features.FeaturesReporter.report(FeaturesReporter.java:97)
	at org.verapdf.features.pb.PBFeatureParser.parseFont(PBFeatureParser.java:878)
	at org.verapdf.features.pb.PBFeatureParser.parseFont(PBFeatureParser.java:867)
	at org.verapdf.features.pb.PBFeatureParser.parseFontFromResources(PBFeatureParser.java:548)
	at org.verapdf.features.pb.PBFeatureParser.getPageTreeFeatures(PBFeatureParser.java:218)
	at org.verapdf.features.pb.PBFeatureParser.getCatalogFeatures(PBFeatureParser.java:164)
	at org.verapdf.features.pb.PBFeatureParser.parseDocumentFeatures(PBFeatureParser.java:132)
	at org.verapdf.features.pb.PBFeatureParser.getFeatures(PBFeatureParser.java:120)
	at org.verapdf.features.pb.PBFeatureParser.getFeaturesCollection(PBFeatureParser.java:110)
	at org.verapdf.model.ModelParser.getFeatures(ModelParser.java:150)
	at org.verapdf.processor.ProcessorImpl.extractFeatures(ProcessorImpl.java:258)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:136)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:109)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:100)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:47)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
	Suppressed: java.lang.NullPointerException
		at org.verapdf.features.FontFeaturesData.close(FontFeaturesData.java:238)
		at org.verapdf.features.FeaturesReporter.report(FeaturesReporter.java:119)
		... 23 more

This is happening for all Plugins!

ilcapitanomark: Marco from Compart

**Comment by bdoubrov** [comment]
Would you please check the latest dev version 1.1.9 (either PDFBOX or GF) available at http://downloads.verapdf.org/dev/

The issue you report should be fixed there.

**Comment by ilcapitanomark** [comment]
Hi, Installed as suggested version 1.1.9. I got now a different problem.

mpi@ubuntu:~/verapdf1.1.9-PDFBOX$ ./verapdf-gui 
Feb 07, 2017 8:23:34 AM org.verapdf.processor.ProcessorImpl extractFeatures
WARNING: Exception caught when extracting features of item
java.lang.NoClassDefFoundError: au/edu/apsr/mtk/base/METSException
	at java.lang.Class.getDeclaredConstructors0(Native Method)
	at java.lang.Class.privateGetDeclaredConstructors(Class.java:2671)
	at java.lang.Class.getConstructor0(Class.java:3075)
	at java.lang.Class.newInstance(Class.java:412)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractorByClassNames(FeaturesPluginsLoader.java:194)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractor(FeaturesPluginsLoader.java:142)
	at org.verapdf.processor.FeaturesPluginsLoader.getExtractorFromConfig(FeaturesPluginsLoader.java:112)
	at org.verapdf.processor.FeaturesPluginsLoader.getAllExtractors(FeaturesPluginsLoader.java:89)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractors(FeaturesPluginsLoader.java:80)
	at org.verapdf.processor.ProcessorImpl.getPlugins(ProcessorImpl.java:308)
	at org.verapdf.processor.ProcessorImpl.extractFeatures(ProcessorImpl.java:290)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:126)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:100)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:47)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: au.edu.apsr.mtk.base.METSException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 23 more

**Comment by ilcapitanomark** [comment]
I've installed also the GF version and I got a different exception:
mpi@ubuntu:~/verapdf-1.1.9-GF$ ./verapdf-gui 
Feb 07, 2017 8:53:11 AM org.verapdf.processor.ProcessorImpl extractFeatures
WARNING: Exception caught when extracting features of item
java.lang.NoClassDefFoundError: org/apache/log4j/Logger
	at org.verapdf.FontSampleExtractor.<clinit>(FontSampleExtractor.java:19)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractorByClassNames(FeaturesPluginsLoader.java:194)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractor(FeaturesPluginsLoader.java:142)
	at org.verapdf.processor.FeaturesPluginsLoader.getExtractorFromConfig(FeaturesPluginsLoader.java:112)
	at org.verapdf.processor.FeaturesPluginsLoader.getAllExtractors(FeaturesPluginsLoader.java:89)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractors(FeaturesPluginsLoader.java:80)
	at org.verapdf.processor.ProcessorImpl.getPlugins(ProcessorImpl.java:308)
	at org.verapdf.processor.ProcessorImpl.extractFeatures(ProcessorImpl.java:290)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:126)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:101)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:48)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: org.apache.log4j.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 25 more

**Comment by BezrukovM** [comment]
Fixes where done in 1.1.19 version, but there is still problems with loading last plugins version and with METS plugin. 
So to run sample plugins now you should do next steps:
1) download the latest version of installer (from 1.1.19 or newer)
2) Install veraPDF with plugins
3) enable all plugins except METS plugin (plugin name in plugins.xml file: METS metadata extraction Sample), i.e. set value of enable attribute to true for all plugins except METS plugin
3) replace 'plugins' folder inside application folder with the archived one in the attached zip file

This archive contains last versions of sample
[plugins.zip](https://github.com/veraPDF/veraPDF-library/files/757430/plugins.zip)
 plugins. There is a little problem with auto-installing last versions and it will be fixed soon.

**Comment by ilcapitanomark** [comment]
Installed 1.1.19, installed the plugins provided in the zip, enabled only "Font Sample" plug-in, exception:
mpi@ubuntu:~/verapdf-1-1-19-PDFBOX$ ./verapdf-gui 
Feb 08, 2017 8:22:35 AM org.verapdf.processor.ProcessorImpl extractFeatures
WARNING: Exception caught when extracting features of item
java.lang.NullPointerException
	at org.verapdf.FontSampleExtractor.inputStreamToByteArray(FontSampleExtractor.java:94)
	at org.verapdf.FontSampleExtractor.getFontFeatures(FontSampleExtractor.java:32)
	at org.verapdf.features.AbstractFontFeaturesExtractor.getFeatures(AbstractFontFeaturesExtractor.java:40)
	at org.verapdf.features.FeaturesReporter.report(FeaturesReporter.java:99)
	at org.verapdf.features.pb.PBFeatureParser.parseFont(PBFeatureParser.java:878)
	at org.verapdf.features.pb.PBFeatureParser.parseFontFromResources(PBFeatureParser.java:548)
	at org.verapdf.features.pb.PBFeatureParser.getPageTreeFeatures(PBFeatureParser.java:218)
	at org.verapdf.features.pb.PBFeatureParser.getCatalogFeatures(PBFeatureParser.java:164)
	at org.verapdf.features.pb.PBFeatureParser.parseDocumentFeatures(PBFeatureParser.java:132)
	at org.verapdf.features.pb.PBFeatureParser.getFeatures(PBFeatureParser.java:120)
	at org.verapdf.features.pb.PBFeatureParser.getFeaturesCollection(PBFeatureParser.java:110)
	at org.verapdf.model.ModelParser.getFeatures(ModelParser.java:168)
	at org.verapdf.processor.ProcessorImpl.extractFeatures(ProcessorImpl.java:290)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:126)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:100)
	at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:47)
	at javax.swing.SwingWorker$1.call(SwingWorker.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at javax.swing.SwingWorker.run(SwingWorker.java:334)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

<img width="1440" alt="screen shot 2017-02-08 at 8 22 51 am" src="https://cloud.githubusercontent.com/assets/13556189/22727209/e7d37b84-edd7-11e6-998a-50aae5aafdef.png">

**Comment by BezrukovM** [comment]
Thank you for feedback. 
This is a problem of the font sample plugin. It has been fixed in file archived in attached .zip. Just replace your plugin file (path: installiationFolder/plugins/fontSample-plugin/fontSample-plugin-0.1.0-SNAPSHOT.jar) with the archived one.
[font.zip](https://github.com/veraPDF/veraPDF-library/files/763095/font.zip)

**Comment by ilcapitanomark** [comment]
Thank you for your prompt reply and for the fix: with this last jar the font sample and other features are working
