### ISSUE TITLE
Missing dependencies

### ISSUE THREAD

**Issue by di-papadopoulos** [veraPDF/veraPDF-library#740]
Trying to using the plugin mechanismus I got the following trace:

exec /Library/Java/JavaVirtualMachines/jdk1.8.0_121.jdk/Contents/Home/bin/java -classpath '/Users/dpa/verapdf/etc:/Users/dpa/verapdf/bin/*' -Dfile.encoding=UTF8 '-Dapp.name=VeraPDF validation CLI' -Dapp.pid=39544 -Dapp.repo=/Users/dpa/verapdf/bin -Dapp.home=/Users/dpa/verapdf -Dbasedir=/Users/dpa/verapdf org.verapdf.cli.VeraPdfCli -x /Users/dpa/JIRA/FOVA/00/79/documents/P0CAR0DCSFC068P03065T02_MES_206894.Acif.afp-160.pdf
Apr 27, 2017 2:13:13 PM org.verapdf.processor.ProcessorImpl extractFeatures
WARNING: Exception caught when extracting features of item
java.lang.NoClassDefFoundError: javax/mail/Authenticator
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:411)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractorByClassNames(FeaturesPluginsLoader.java:177)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractor(FeaturesPluginsLoader.java:142)
	at org.verapdf.processor.FeaturesPluginsLoader.getExtractorFromConfig(FeaturesPluginsLoader.java:112)
	at org.verapdf.processor.FeaturesPluginsLoader.getAllExtractors(FeaturesPluginsLoader.java:89)
	at org.verapdf.processor.FeaturesPluginsLoader.loadExtractors(FeaturesPluginsLoader.java:80)
	at org.verapdf.processor.ProcessorImpl.getPlugins(ProcessorImpl.java:308)
	at org.verapdf.processor.ProcessorImpl.extractFeatures(ProcessorImpl.java:290)
	at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:126)
	at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
	at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
	at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
	at org.verapdf.cli.VeraPdfCliProcessor.processFiles(VeraPdfCliProcessor.java:140)
	at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:114)
	at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:99)
Caused by: java.lang.ClassNotFoundException: javax.mail.Authenticator
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 27 more

Investigating the problem I found the following:
my plugin (fontvalidator) has dependency to the 
<dependency>
	<groupId>org.slf4j</groupId>
	<artifactId>slf4j-log4j12</artifactId>
	<version>1.7.21</version>                                				
</dependency>

as the verapdf application has also.
Now the problem comes from the loader extractor where it checks if the plugin is valid.
The loader extractor will read all the classes from my plugin and it will try to find and load them. The order to find and load the class is the following:
1) check the system libraries
2) check the application class path
3) check the plugin manifest

As it is used the same slf4j-log4j12 it will be loaded by the 2nd search, and it will try to load all the dependencies of the slf4j-log4j12. As in the class path of the verapdf doesn't exist the javax.jms.jar and the mail-1.4.1.jar there is an exception which breaks the execution.

As I cannot change the order of searching at the class path I would like to ask you to add as dependencies the missing jar files.

**Comment by carlwilson** [comment]
This sounds as though the answer should be to either change the plugins to use native Java login or if that's not possible to ensure that the plugin jar is "fat" with the appropriate jars packaged.

**Comment by di-papadopoulos** [comment]
Is there any progress?

**Comment by carlwilson** [comment]
Hi @di-papadopoulos we're looking at this now and will get a fix out for the upcoming release next week or a clear statement intent if there's a problem.

**Comment by carlwilson** [comment]
OK, I have an answer, I'm not sure that we should be adding the jars to the veraPDF library given that they're the old Oracle Jars. I've managed to reproduce the problem and then fix it by changing the packaging of the plugin project. In essence I had to explicitly add the runtime dependencies in my plugin modules POM, e.g. `fontSample-plugin/pom.xml`:
```xml
  <dependencies>
    <dependency>
      <groupId>org.verapdf</groupId>
      <artifactId>core</artifactId>
    </dependency>
    <dependency>
      <groupId>org.slf4j</groupId>
      <artifactId>slf4j-log4j12</artifactId>
      <version>1.7.21</version>
    </dependency>
    <dependency>
      <groupId>javax.jms</groupId>
      <artifactId>javax.jms-api</artifactId>
      <version>2.0.1</version>
    </dependency>
    <dependency>
      <groupId>javax.mail</groupId>
      <artifactId>javax.mail-api</artifactId>
      <version>1.6.0</version>
    </dependency>
  </dependencies>
```
Next I created an assembly file for the plugin project as `fontSample-plugin/src/assembly/fontSample-assembly.xml`:
```xml
<assembly
    xmlns="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.3"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://maven.apache.org/plugins/maven-assembly-plugin/assembly/1.1.3 http://maven.apache.org/xsd/assembly-1.1.3.xsd">
    <id>fontSample-assembly</id>
    <formats>
        <format>jar</format>
    </formats>
    <includeBaseDirectory>false</includeBaseDirectory>
    <dependencySets>
        <dependencySet>
            <outputDirectory>/</outputDirectory>
            <useProjectArtifact>false</useProjectArtifact>
            <unpack>true</unpack>
            <scope>runtime</scope>
            <excludes>
              <exclude>org.verapdf:*</exclude>
              <exclude>org.mozilla:*</exclude>
            </excludes>
        </dependencySet>
    </dependencySets>
    <fileSets>
        <fileSet>
            <outputDirectory>/</outputDirectory>
            <directory>${project.build.outputDirectory}</directory>
        </fileSet>
    </fileSets>
</assembly>
```
This excludes the veraPDF dependencies explicitly but allows artefacts through. We then need to add the assembly plugin to the build, again using `fontSample-plugin/pom.xml`:
```xml
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-assembly-plugin</artifactId>
        <configuration>
          <descriptors>
            <descriptor>src/assembly/fontSample-assembly.xml</descriptor>
          </descriptors>
        </configuration>
        <executions>
          <execution>
            <id>make-assembly</id> <!-- this is used for inheritance merges -->
            <phase>package</phase> <!-- bind to the packaging phase -->
            <goals>
              <goal>single</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```
After this issuing `mvn clean install` will create new fat jars with the dependencies:
```shell
cfw@dm-wrkstn:~/proj/veraPDF/dev/plugins$ ls -alh fontSample-plugin/target/
total 1.6M
drwxrwxr-x 7 cfw cfw 4.0K Aug  4 16:25 .
drwxrwxr-x 5 cfw cfw 4.0K Aug  4 16:25 ..
drwxrwxr-x 2 cfw cfw 4.0K Aug  4 16:25 archive-tmp
drwxrwxr-x 3 cfw cfw 4.0K Aug  4 16:25 classes
-rw-rw-r-- 1 cfw cfw 1.5M Aug  4 16:25 fontSample-plugin-0.1.0-SNAPSHOT-fontSample-assembly.jar
-rw-rw-r-- 1 cfw cfw 4.6K Aug  4 16:25 fontSample-plugin-0.1.0-SNAPSHOT.jar
drwxrwxr-x 3 cfw cfw 4.0K Aug  4 16:25 generated-sources
drwxrwxr-x 2 cfw cfw 4.0K Aug  4 16:25 maven-archiver
drwxrwxr-x 3 cfw cfw 4.0K Aug  4 16:25 maven-status
```
it's the one that's 1.5M large called: `fontSample-plugin-0.1.0-SNAPSHOT-fontSample-assembly.jar`, and using this as the plugin jar works well. I'll close this unless I hear differently on 11/08/2017.
