### ISSUE TITLE
Problem with colorspaces following recent model update?

### ISSUE THREAD

**Issue by carlwilson** [veraPDF/veraPDF-library#753]
I'm NOT 100% sure that this is the cause but I think that this PR https://github.com/veraPDF/veraPDF-model/pull/138 has led to this file: [Asana-Sept15.pdf](https://github.com/veraPDF/veraPDF-library/files/1033773/Asana-Sept15.pdf), throwing this exception:
```console
<report>
  <buildInformation>
    <releaseDetails id="core" version="1.5.10" buildDate="2017-05-26T14:45:00+01:00"></releaseDetails>
    <releaseDetails id="gui" version="1.5.30-PDFBOX" buildDate="2017-05-26T15:41:00+01:00"></releaseDetails>
    <releaseDetails id="pdfbox-validation-model" version="1.5.14" buildDate="2017-05-26T14:47:00+01:00"></releaseDetails>
  </buildInformation>
  <jobsException in thread "main" java.lang.IllegalAccessError: OpColor has not access to this method or has not colorSpace link.
        at org.verapdf.model.GenericModelObject.getLinkedObjects(GenericModelObject.java:35)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:242)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:187)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:131)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:102)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.cli.VeraPdfCliProcessor.processFiles(VeraPdfCliProcessor.java:154)
        at org.verapdf.cli.VeraPdfCliProcessor.processPaths(VeraPdfCliProcessor.java:128)
        at org.verapdf.cli.VeraPdfCli.main(VeraPdfCli.java:95)
```
 It affects both CLI and GUI.

The lack of test results seems to back up the theory: http://tests.verapdf.org/1.5/27/

**Comment by shem-sergey** [comment]
Yes, probably you started validation in the moment when model changes were already merged but pdfbox-validation not.
I tested this file on my local version and on last dev version to be sure, everything works. So this issue can be closed.
