### ISSUE TITLE
validator throws exception on veraPDF-corpus/PDF_A-1b/6.1 File structure/6.1.2 File header/veraPDF test suite 6-1-2-t01-fail-a.pdf

### ISSUE THREAD

**Issue by ravn** [veraPDF/veraPDF-library#894]
Running
```
   PDFAFlavour flavour = PDFAFlavour.byFlavourId(flavorId);
        PDFAValidator validator = Foundries.defaultInstance().createValidator(flavour, false);
        PDFAParser loader = Foundries.defaultInstance().createParser(inputStream, flavour);
        ValidationResult result = validator.validate(loader);

        // do in-memory generation of XML byte array - as we need to pass it to Fedora we need it to fit in memory anyway.

        ByteArrayOutputStream baos = new ByteArrayOutputStream();
        XmlSerialiser.toXml(result, baos, prettyXml, false);
        final byte[] byteArray = baos.toByteArray();
        return byteArray;
```

on veraPDF-corpus/PDF_A-1b/6.1 File structure/6.1.2 File header/veraPDF test suite 6-1-2-t01-fail-a.pdf cause the validator to throw an exception:

```
java.lang.RuntimeException: invoking VeraPDF validation
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.verapdf.VeraPDFValidator.apply(VeraPDFValidator.java:48)
	at dk.kb.verapdf.qa.TestOnCorpus.checkForLeakingFileDescriptorsOnWholeCorpus(TestOnCorpus.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: org.verapdf.core.ValidationException: Caught unexpected runtime exception during validation
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:104)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.verapdf.VeraPDFValidator.apply0(VeraPDFValidator.java:67)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.verapdf.VeraPDFValidator.apply(VeraPDFValidator.java:44)
	... 23 more
Caused by: org.mozilla.javascript.WrappedException: Wrapped java.lang.NullPointerException
	at org.mozilla.javascript.Context.throwAsScriptRuntimeEx(Context.java:1773)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:183)
	at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
	at org.mozilla.javascript.optimizer.OptRuntime.callProp0(OptRuntime.java:119)
	at org.mozilla.javascript.gen.c316._c0(unnamed script:0)
	at org.mozilla.javascript.gen.c316.call(unnamed script)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:398)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3065)
	at org.mozilla.javascript.gen.c316.call(unnamed script)
	at org.mozilla.javascript.gen.c316.exec(unnamed script)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkObjWithRule(BaseValidator.java:389)
	at org.verapdf.pdfa.validation.validators.BaseValidator.firstProcessObjectWithRule(BaseValidator.java:325)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkAllRules(BaseValidator.java:297)
	at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:183)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:131)
	at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:102)
	... 25 more
Caused by: java.lang.NullPointerException
	at org.verapdf.pd.PDObject.knownKey(PDObject.java:65)
	at org.verapdf.gf.model.impl.pd.GFPDDocument.getcontainsAA(GFPDDocument.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
	... 39 more
```

**Comment by BezrukovM** [comment]
I can not reproduce that issue with the latest dev version. Here is the code which I have tried to use for reproducing:

**Comment by ravn** [comment]
What do you consider the latest "dev" version?  When building from source I find that the pom.xml have an older version than the ones in the repository so the repository artifacts are used even if the source is newer than them.

**Comment by BezrukovM** [comment]
I have found where the problem has been previously. It has been fixed in last dev versions.
@ravn can you double check that on your machine, please? Just to be sure, that you don't have that exception too.
Thanks.
Last dev versions: 
veraPDF-parser - 1.9.33
veraPDF-library - 1.9.7
veraPDF-validation - 1.9.55

**Comment by ravn** [comment]
I do not have this code handy anymore, and cannot easily check.  Out of curiosity - is there a test being run by Jenkins that run this code on the whole corpus?
