### ISSUE TITLE
Improve logging errors and warnings

### ISSUE THREAD

**Issue by ravn** [veraPDF/veraPDF-library#926]
## Dev Effort
1D

## Description
We have a PDF file apparently containing a bad number.  This is reported in the log.  Could this be disabled and just listed in the report returned, please?

```
nov. 14, 2017 5:18:31 PM org.verapdf.parser.PDFParser parseHeader
WARNING: Can't parse the header version.
java.lang.NumberFormatException: For input string: "a.4"
	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
	at sun.misc.FloatingDecimal.parseFloat(FloatingDecimal.java:122)
	at java.lang.Float.parseFloat(Float.java:451)
	at org.verapdf.parser.PDFParser.parseHeader(PDFParser.java:140)
	at org.verapdf.parser.PDFParser.getHeader(PDFParser.java:76)
	at org.verapdf.io.Reader.init(Reader.java:146)
	at org.verapdf.io.Reader.<init>(Reader.java:72)
	at org.verapdf.cos.COSDocument.initReader(COSDocument.java:120)
	at org.verapdf.cos.COSDocument.<init>(COSDocument.java:99)
	at org.verapdf.pd.PDDocument.<init>(PDDocument.java:65)
	at org.verapdf.gf.model.GFModelParser.<init>(GFModelParser.java:70)
	at org.verapdf.gf.model.GFModelParser.createModelWithFlavour(GFModelParser.java:93)
	at org.verapdf.pdfa.VeraFoundry.createParser(VeraFoundry.java:71)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.verapdf.VeraPDFValidator.apply0(VeraPDFValidator.java:66)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.verapdf.VeraPDFValidator.apply(VeraPDFValidator.java:44)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.verapdf.VeraPDFValidator.apply(VeraPDFValidator.java:22)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.invokeVeraPDFOnPhysicalFiles1(VeraPDFInvokeMain.java:246)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.lambda$invokeVeraPDFOnPhysicalFiles0$11(VeraPDFInvokeMain.java:168)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.streams.IdValue.flatMap(IdValue.java:89)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.lambda$null$8(VeraPDFInvokeMain.java:149)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:267)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.lambda$processChildDomsId$10(VeraPDFInvokeMain.java:150)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.lambda$null$1(VeraPDFInvokeMain.java:113)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.streams.IdValue.map(IdValue.java:63)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.lambda$null$2(VeraPDFInvokeMain.java:113)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1374)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:270)
	at java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:419)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.LongPipeline.reduce(LongPipeline.java:438)
	at java.util.stream.LongPipeline.sum(LongPipeline.java:396)
	at java.util.stream.ReferencePipeline.count(ReferencePipeline.java:526)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain$VeraPDFInvokeModule.lambda$provideTool$5(VeraPDFInvokeMain.java:130)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.harness.AutonomousPreservationToolHelper.execute(AutonomousPreservationToolHelper.java:91)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.harness.AutonomousPreservationToolHelper.execute(AutonomousPreservationToolHelper.java:64)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.VeraPDFInvokeMain.main(VeraPDFInvokeMain.java:72)
	at dk.statsbiblioteket.digital_pligtaflevering_aviser.tools.main.localhost.VeraPDFInvokeAllLocalhostLauncher.main(VeraPDFInvokeAllLocalhostLauncher.java:18)

```

**Comment by bdoubrov** [comment]
this error message goes into stderr. So, it can be disabled by just adding 
`2>null` 
to the command line. Or you expected also a different error in the report?

**Comment by ravn** [comment]
We are using this code as a library, so the 2>null approach will also discard any output our code sends to standard error which we usually do not want.

Please do not output to standard error unless something really is very wrong.

**Comment by BezrukovM** [comment]
wrong header worning has been fixed (level changed to fine and hence will not be reported in err stream), but the problem still left. We have to add some mechanism that will allow users to set necessary logging level.

**Comment by carlwilson** [comment]
Perhaps we still need a specific issue to allow fine grained control of the logging level.

**Comment by bdoubrov** [comment]
yes, indeed. I would suggest to handle this in the next release as well

**Comment by carlwilson** [comment]
Logging has been improved significantly and closing this now.
