### ISSUE TITLE
Command line (CLI) and GUI reporting an OutOfMemory exception

### ISSUE THREAD

**Issue by allock** [veraPDF/veraPDF-library#952]
I obtained an error during processing a PDF with a large number of pages (1397 pages):

╨░╨┐╤А 09, 2018 10:35:30 AM org.verapdf.processor.ProcessorImpl validate
WARNING: OutOfMemory caught when validaing item
java.lang.OutOfMemoryError: Java heap space
        at java.util.Arrays.copyOfRange(Unknown Source)
        at java.lang.String.<init>(Unknown Source)
        at java.lang.StringBuilder.toString(Unknown Source)
        at org.verapdf.pdfa.validation.validators.BaseValidator.addAllLinkedObjects(BaseValidator.java:272)
        at org.verapdf.pdfa.validation.validators.BaseValidator.checkNext(BaseValidator.java:186)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:131)
        at org.verapdf.pdfa.validation.validators.BaseValidator.validate(BaseValidator.java:102)
        at org.verapdf.processor.ProcessorImpl.validate(ProcessorImpl.java:219)
        at org.verapdf.processor.ProcessorImpl.process(ProcessorImpl.java:120)
        at org.verapdf.processor.BatchFileProcessor.processItem(BatchFileProcessor.java:98)
        at org.verapdf.processor.BatchFileProcessor.processList(BatchFileProcessor.java:74)
        at org.verapdf.processor.AbstractBatchProcessor.process(AbstractBatchProcessor.java:102)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:123)
        at org.verapdf.gui.ValidateWorker.doInBackground(ValidateWorker.java:58)
        at javax.swing.SwingWorker$1.call(Unknown Source)
        at java.util.concurrent.FutureTask.run(Unknown Source)
        at javax.swing.SwingWorker.run(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
        at java.lang.Thread.run(Unknown Source)

[Robinson-ProCsharp3.pdf](https://github.com/veraPDF/veraPDF-library/files/1888874/Robinson-ProCsharp3.pdf)

**Comment by BezrukovM** [comment]
Both last release and dev GF versions of veraPDF (1.11.16 and 1.10.6) works fine on my machine:
Linux Debian (Linux bezrukov 3.16.0-5-amd64 #1 SMP Debian 3.16.51-3+deb8u1 (2018-01-08) x86_64 GNU/Linux)
Java 8 (java version "1.8.0_161")
Java heap space max 2GB

Can you provide us more information about your machine? Namely:
- version of veraPDF (GreenField or PDFBox and version number)
- OS
- Java version
- Java heap space
And have you tried to increase your java heap space? CLI shall show an example how to do that when you obtain that exception during CLI usage.

**Comment by allock** [comment]
Many thanks for your answer!
I increased the java heap space and the problem was solved!
Best regards!
